/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Management.Word;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Remove extends javax.swing.JDialog {

    /**
     * Creates new form Remove
     */
     private HomeJFre home;
    public Remove(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (HomeJFre) parent;
    }
     private void removeFile(Word rem) throws FileNotFoundException, IOException{
       
        File tempFile = new File("temp.txt"); // đây là file temp, trước đó không được tạo sẵn
        FileWriter fw;
        BufferedWriter bw = null; // cái này để ghi vào file temp
        Scanner sc = new Scanner(new File("data1.txt")); // đọc dữ liệu file oldFile
        try {
            fw = new FileWriter(tempFile,true); // try catch này khởi tạo thôi
            bw = new BufferedWriter(fw);
        } catch (IOException e) {
            e.printStackTrace();
        }
        while (sc.hasNextLine()) {
            String str = sc.nextLine();
            if(!str.matches(rem.getWord_target()+".*"))
                try {
                    bw.write(str + "\n");
                } catch (IOException e) {
                    e.printStackTrace();
                }
        }
        try {
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        sc.close();
        try {
             File oldFile = new File("data1.txt");
            if (oldFile.delete()) {
                JOptionPane.showMessageDialog(rootPane,"oce!");
            } else {
                JOptionPane.showMessageDialog(rootPane,"sịt!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
         File newFile = new File("data1.txt");
        tempFile.renameTo(newFile);
    
        
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texeRemove = new javax.swing.JTextField();
        ButtonAcp = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonAcp.setText("Remove");
        ButtonAcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAcpActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(ButtonAcp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(texeRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(texeRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAcp)
                    .addComponent(Exit))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ButtonAcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAcpActionPerformed
         String word_remove = texeRemove.getText();
          boolean check = true;
           if (word_remove.length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Word không được để trống!");
            check = false;
        } 
       
        if (word_remove.matches("[^a-zA-Z]+")){
             JOptionPane.showMessageDialog(rootPane,"Word lỗi định dạng!");
            check = false;
        } 
        if (check) {
             Word rem = new Word(null,null);
            for (Word word : home.getListWord()) {
                if(word.getWord_target().equals(word_remove)) {
                    rem = word;
                    break;}
            }
             try {
                 removeFile(rem);
                  JOptionPane.showMessageDialog(rootPane,"oce rồi baeee ơi !");
             } catch (IOException ex) {
                 Logger.getLogger(Remove.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_ButtonAcpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Remove dialog = new Remove(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAcp;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField texeRemove;
    // End of variables declaration//GEN-END:variables
}
